"""GravAI core: the foundations every app and agent package builds on."""

from __future__ import annotations

from .audit import (
    GENESIS_HASH,
    AuditActions,
    AuditEntry,
    ChainVerification,
    canonical_json,
    canonical_timestamp,
    verify_chain,
)
from .auth import Principal, Role, Scope, decode_token, issue_dev_token, scopes_for_roles
from .db import admin_session_scope, dispose_engine, get_engine, healthcheck, session_scope
from .errors import (
    ConnectorError,
    DocJobFailed,
    DocJobTimeout,
    Forbidden,
    GravAIError,
    MissingTenantContext,
    NotFound,
    QuotaExhausted,
    SarvamAuthError,
    SarvamRateLimited,
    SarvamServerError,
    SchemaViolation,
    TenantMismatch,
    Unauthenticated,
    ValidationFailed,
)
from .models import (
    TENANT_SCOPED_TABLES,
    AgentRun,
    AgentStep,
    ApiKey,
    Application,
    AppUser,
    AuditLog,
    Base,
    Consent,
    CostLedger,
    PromptVersion,
    RateCard,
    Task,
    Tenant,
    UserRole,
    Workflow,
    WorkflowRun,
    WorkflowVersion,
)
from .models import Role as RoleModel
from .money import as_percent, emi, foir, format_inr, format_lakh_crore, ltv
from .pii import aadhaar_last4, is_valid_gstin, is_valid_pan, mask_aadhaar, redact_text
from .repositories import AuditRepository, get_or_404, tenant_query
from .runs import ESCALATION_ROLE, persist_run, record_consent, resolve_task
from .settings import PollSchedule, Settings, get_settings
from .telemetry import configure_logging, configure_tracing, get_logger
from .tenancy import (
    current_tenant_id,
    no_tenant,
    require_tenant_id,
    tenant_scope,
)
from .time_utils import IST, format_ddmmyyyy, ist_now, utc_now, within_call_window

__version__ = "0.1.0"

__all__ = [
    "ESCALATION_ROLE",
    "GENESIS_HASH",
    "IST",
    "TENANT_SCOPED_TABLES",
    "AgentRun",
    "AgentStep",
    "ApiKey",
    "AppUser",
    "Application",
    "AuditActions",
    "AuditEntry",
    "AuditLog",
    "AuditRepository",
    "Base",
    "ChainVerification",
    "ConnectorError",
    "Consent",
    "CostLedger",
    "DocJobFailed",
    "DocJobTimeout",
    "Forbidden",
    "GravAIError",
    "MissingTenantContext",
    "NotFound",
    "PollSchedule",
    "Principal",
    "PromptVersion",
    "QuotaExhausted",
    "RateCard",
    "Role",
    "RoleModel",
    "SarvamAuthError",
    "SarvamRateLimited",
    "SarvamServerError",
    "SchemaViolation",
    "Scope",
    "Settings",
    "Task",
    "Tenant",
    "TenantMismatch",
    "Unauthenticated",
    "UserRole",
    "ValidationFailed",
    "Workflow",
    "WorkflowRun",
    "WorkflowVersion",
    "__version__",
    "aadhaar_last4",
    "admin_session_scope",
    "as_percent",
    "canonical_json",
    "canonical_timestamp",
    "configure_logging",
    "configure_tracing",
    "current_tenant_id",
    "decode_token",
    "dispose_engine",
    "emi",
    "foir",
    "format_ddmmyyyy",
    "format_inr",
    "format_lakh_crore",
    "get_engine",
    "get_logger",
    "get_or_404",
    "get_settings",
    "healthcheck",
    "is_valid_gstin",
    "is_valid_pan",
    "issue_dev_token",
    "ist_now",
    "ltv",
    "mask_aadhaar",
    "no_tenant",
    "persist_run",
    "record_consent",
    "redact_text",
    "require_tenant_id",
    "resolve_task",
    "scopes_for_roles",
    "session_scope",
    "tenant_query",
    "tenant_scope",
    "utc_now",
    "verify_chain",
    "within_call_window",
]
