"""Baseline schema, with row-level security on PostgreSQL.

The tables are created from the declarative metadata so the models stay the
single source of truth for the initial revision; subsequent revisions are
autogenerated diffs in the normal way.

Two things are applied only on PostgreSQL, because SQLite has neither feature:

* **Row-level security** on every tenant-scoped table, so a query that forgets
  its tenant filter returns nothing instead of another tenant's rows.
* **An append-only trigger** on ``audit_log``, so the hash chain cannot be
  quietly rewritten by anything holding a database connection.

On SQLite the service layer is the only guard (DECISIONS.md D-002).

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-14
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from gravai_core.models import TENANT_SCOPED_TABLES, Base

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: The GUC the policies read. Set per transaction by gravai_core.db.bind_tenant.
TENANT_GUC = "gravai.tenant_id"


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def _apply_row_level_security() -> None:
    """Force every tenant-scoped table to filter by the session's tenant.

    ``FORCE ROW LEVEL SECURITY`` matters: without it the table owner bypasses the
    policy, which would make the protection vanish in exactly the deployment
    where the application connects as the owner.
    """
    for table in TENANT_SCOPED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (tenant_id::text = current_setting('{TENANT_GUC}', true))
            WITH CHECK (tenant_id::text = current_setting('{TENANT_GUC}', true))
            """
        )


def _apply_audit_immutability() -> None:
    """Reject UPDATE and DELETE on audit_log at the database level."""
    op.execute(
        """
        CREATE OR REPLACE FUNCTION gravai_audit_is_append_only()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION
                'audit_log is append-only; % on audit_log is not permitted',
                TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_append_only
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION gravai_audit_is_append_only();
        """
    )


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)

    if _is_postgres():
        _apply_row_level_security()
        _apply_audit_immutability()


def downgrade() -> None:
    bind = op.get_bind()

    if _is_postgres():
        op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log")
        op.execute("DROP FUNCTION IF EXISTS gravai_audit_is_append_only()")
        for table in TENANT_SCOPED_TABLES:
            op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
            op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    Base.metadata.drop_all(bind=bind)


__all__ = ["down_revision", "revision", "upgrade", "downgrade", "sa"]
