"""GravAI agents.

An agent is a prompt, a validated output contract, a set of tools and a set of
guardrails that run in code after every model call. The catalog says which
agents exist; the registry says which of them can actually run.
"""

from __future__ import annotations

from .base import Agent, AgentContext, AgentResult, AgentStep
from .catalog import AGENT_CATALOG, AgentSpec, AgentTier, get_agent, list_agents
from .conduct import ConductReport, ConductViolation, check_transcript, check_utterance, may_call
from .guardrails import (
    ValidationReport,
    detect_injection_echo,
    run_all,
    scan_pii_leak,
    scan_protected_attributes,
    validate_citations,
    validate_grounding,
)
from .implementations import (
    AaDataAgent,
    AaDataOutput,
    BankStatementAnalyticsAgent,
    BankStatementOutput,
    CallOutcome,
    CallState,
    CaseAllocationAgent,
    CaseAllocationOutput,
    CdiOutput,
    Counterparty,
    CreditAppraisalAgent,
    CreditAppraisalOutput,
    CustomerDataIntelligenceAgent,
    CustomerSignal,
    DocIntelligenceAgent,
    DocIntelligenceOutput,
    GstReturn,
    KycOutput,
    KycVerificationAgent,
    MsmeOutput,
    MsmeUnderwritingAgent,
    OnboardingAssistantAgent,
    OnboardingOutput,
    OpsReportOutput,
    OpsResearchAgent,
    RiskOutput,
    RiskScoringAgent,
    SmartMandateAgent,
    SmartMandateOutput,
    SpeechAnalyticsAgent,
    SpeechAnalyticsOutput,
    Transaction,
    VoiceCollectionsAgent,
    VoiceCollectionsOutput,
)
from .namematch import NameMatch, match_names, normalise
from .pipeline import (
    CollectionsResult,
    PipelineResult,
    run_collections_pipeline,
    run_credit_pipeline,
    transactions_from_documents,
)
from .prompting import (
    PROTECTED_ATTRIBUTES,
    PromptContext,
    build_system_prompt,
    document_block,
    input_block,
)
from .registry import (
    IMPLEMENTATIONS,
    build_agent,
    implemented_ids,
    is_implemented,
    pending_ids,
)
from .routing import DIGITISE_TYPES, DocumentType, classify_declared, route_for, schema_hint_for
from .schemas import AgentOutput, Band, Citation, FieldValue, Flag, FlagType
from .scorecard import SCORECARD_VERSION, RiskFeatures, ScoreResult, population_stability_index
from .scorecard import score as score_risk
from .volume_model import (
    VolumeAssumptions,
    VolumeModel,
    build_volume_model,
    routing_scenarios,
)
from .volume_model import backlog as backlog_projection

__version__ = "0.1.0"

__all__ = [
    "AGENT_CATALOG",
    "DIGITISE_TYPES",
    "IMPLEMENTATIONS",
    "PROTECTED_ATTRIBUTES",
    "SCORECARD_VERSION",
    "AaDataAgent",
    "AaDataOutput",
    "Agent",
    "AgentContext",
    "AgentOutput",
    "AgentResult",
    "AgentSpec",
    "AgentStep",
    "AgentTier",
    "Band",
    "BankStatementAnalyticsAgent",
    "BankStatementOutput",
    "CallOutcome",
    "CallState",
    "CaseAllocationAgent",
    "CaseAllocationOutput",
    "CdiOutput",
    "Citation",
    "CollectionsResult",
    "ConductReport",
    "ConductViolation",
    "Counterparty",
    "CreditAppraisalAgent",
    "CreditAppraisalOutput",
    "CustomerDataIntelligenceAgent",
    "CustomerSignal",
    "DocIntelligenceAgent",
    "DocIntelligenceOutput",
    "DocumentType",
    "FieldValue",
    "Flag",
    "FlagType",
    "GstReturn",
    "KycOutput",
    "KycVerificationAgent",
    "MsmeOutput",
    "MsmeUnderwritingAgent",
    "NameMatch",
    "OnboardingAssistantAgent",
    "OnboardingOutput",
    "OpsReportOutput",
    "OpsResearchAgent",
    "PipelineResult",
    "PromptContext",
    "RiskFeatures",
    "RiskOutput",
    "RiskScoringAgent",
    "ScoreResult",
    "SmartMandateAgent",
    "SmartMandateOutput",
    "SpeechAnalyticsAgent",
    "SpeechAnalyticsOutput",
    "Transaction",
    "ValidationReport",
    "VoiceCollectionsAgent",
    "VoiceCollectionsOutput",
    "VolumeAssumptions",
    "VolumeModel",
    "__version__",
    "backlog_projection",
    "build_agent",
    "build_system_prompt",
    "build_volume_model",
    "check_transcript",
    "check_utterance",
    "classify_declared",
    "detect_injection_echo",
    "document_block",
    "get_agent",
    "implemented_ids",
    "input_block",
    "is_implemented",
    "list_agents",
    "match_names",
    "may_call",
    "normalise",
    "pending_ids",
    "population_stability_index",
    "route_for",
    "routing_scenarios",
    "run_all",
    "run_collections_pipeline",
    "run_credit_pipeline",
    "scan_pii_leak",
    "scan_protected_attributes",
    "schema_hint_for",
    "score_risk",
    "transactions_from_documents",
    "validate_citations",
    "validate_grounding",
]
